### PR TITLE
Version 1.0.0.3

### PR DESCRIPTION
**Pull request by rahulroyrdx001**
### Version 1.0.0.3

In this version, we develop the below features

**Features:**
1. Add background gradient color (#F8F6E3 ---> #97E7E1)
2. Add Analytics and Working area
3. Inside the working area we built different sections as per the design (Todo, In-progress, Review, Done)
4. Add the color to the Sections and handle the opacity.
5. Add the shadow effect to the elements.

**Before:**

Screenshot (489)

**After:**

Screenshot (490)

### CODE REVIEW

**Comment by rahulroyrdx001** [comment]
If any changes require pls add your inputs.

**Review by Anupriyakumarii — APPROVED** [review]
No changes needs to be done. All changes have been implemented in accordance with our requirements.

**Comment by rahulroyrdx001** [comment]
> No changes needs to be done. All changes have been implemented in accordance with our requirements.

Thank you madam for your review.👍❤️

**Comment by rahulroyrdx001** [comment]
Based on the validation by @Anupriyakumarii and @rahulroyrdx001 we are proceeding with the merge.

**Pull request merged**
