### PR TITLE
Version 1.0.0.4

### PR DESCRIPTION
**Pull request by rahulroyrdx001**
### Version 1.0.0.4

In this version, we worked on background elements and their styling. All the changes are given below. In this version, we achieve **80 percent** of the desired output.

**Before:**

Screenshot (490)

**After:
Chrome:**
 
Screenshot (492)

**Edge:**

Screenshot (491)

### CODE REVIEW

**Comment by rahulroyrdx001** [comment]
@Anupriyakumarii Madam I have made some changes in the background  and need your approval to merge this changes. If any changes are require please add your inputs.

**Comment by rahulroyrdx001** [comment]
@Anupriyakumarii  madam  I am looking for the fonts which is best suitable for this project ,So I looking for some suggestion from your end.

**Review by Anupriyakumarii — APPROVED** [review]
Changes you have done are  meeting the requirements.

**Comment by Anupriyakumarii** [comment]
> @Anupriyakumarii madam I am looking for the fonts which is best suitable for this project ,So I looking for some suggestion from your end.

Yeah i have some couple of fonts which we can use in this project.
1.Roboto
2.Open Sans
3.Montserrat
4.Source Sans Pro

https://fonts.google.com/
you can refer this link to check these four fonts

based on that we'll take the call.

**Comment by rahulroyrdx001** [comment]
> Changes you have done are meeting the requirements.

Thank @Anupriyakumarii  madam for your feedback. As per the @Anupriyakumarii and @rahulroyrdx001 validation, we are proceed, with the merge.

**Comment by rahulroyrdx001** [comment]
> > @Anupriyakumarii madam I am looking for the fonts which is best suitable for this project ,So I looking for some suggestion from your end.
> 
> Yeah i have some couple of fonts which we can use in this project. 1.Roboto 2.Open Sans 3.Montserrat 4.Source Sans Pro
> 
> https://fonts.google.com/ you can refer this link to check these four fonts
> 
> based on that we'll take the call.

Thank you @Anupriyakumarii  madam for your suggestion. We will definitely look into it.

**Pull request merged**
