### PR TITLE
Version 1.0.0.6

### PR DESCRIPTION
**Pull request by rahulroyrdx001**
### Version 1.0.0.6

In this version, we worked on Modal. We worked on the styling part of the Modal. But we have to work on the responsiveness of Modal.

**Demo:**

Screenshot (497)

### CODE REVIEW

**Comment by rahulroyrdx001** [comment]
@Anupriyakumarii  madam check the Modal part.

**Review by Anupriyakumarii — APPROVED** [review]
Model page design is as expected, no changes needs to be done.

**Comment by rahulroyrdx001** [comment]
> Model page design is as expected, no changes need to be done.

But it is not responsive , so need your help on it

**Comment by rahulroyrdx001** [comment]
As per the validation by @Anupriyakumarii and @rahulroyrdx001, we are going to merge these changes.

**Pull request merged**
