### PR TITLE
Version 1.0.0.5

### PR DESCRIPTION
**Pull request by rahulroyrdx001**
### Version 1.0.05

In this version, we developed the below features. In this version, **we need to focus more on concepts like drag and drop in React Beautiful dnd**. In the upcoming version, we need to focus on code cleanup .*For the data we used an external auto JSON data creator, in the future we have to replace it with practical data.

here is the documentation of react beautiful dnd: https://github.com/atlassian/react-beautiful-dnd

**Features:**
1. We added a temporary logo to the navbar.
2. We implemented the Drag and Drop feature using React Beautiful dnd. 
3. We also implement the states of the components as per the functionality.

**Pending:**
1. Need to Implement the desired styling. Adopt the Page Object Model by creating separate component and styling files for enhanced maintainability and consistency.
2. Need to develop Search functionality.
3. Need to work on the backend database.
4. Login page.
5. Profile section.

**Before:**

Screenshot (493)

**After:**

https://github.com/rahulroyrdx001/Task-Management-System/assets/76472099/633de485-ca7e-4f61-836c-a10261d6fdf6

### CODE REVIEW

**Comment by rahulroyrdx001** [comment]
This is the very vital feature of our web app . Many concepts we need to discuss @Anupriyakumarii Madam. So Please look into it and give your feedback for future processes. Thank you for your efforts on the Authentication page.🙌🙌

**Comment by Anupriyakumarii** [comment]
All these queries are created manually or from create button??

**Review by Anupriyakumarii — COMMENTED** [review]
when the task is done we have to shift our queries box manually or we are providing any other functionality for it?

**Review by Anupriyakumarii — APPROVED** [review]
Till this functionality everything is working fine.

**Comment by rahulroyrdx001** [comment]
> All these queries are created manually or from the create button??

This is fetched from an API. Which has some predefined data sets.  We yet not start the functionality of the Create button. Going forward to the upcoming version we will work on it.

**Comment by rahulroyrdx001** [comment]
> Till this functionality everything is working fine.



> when the task is done we have to shift our queries box manually or we are providing any other functionality for it?

As per what I understood from your question, if we move that task to Done it should reflect to Done.

**Comment by rahulroyrdx001** [comment]
In the upcoming version, we are going to work on code cleanup and develop our separate components. As per the validation by @Anupriyakumarii  and @rahulroyrdx001, we are going to merge this feature.

**Pull request merged**
